export const GENRES = [
  "Visual Novel",
  "Sandbox",
  "RPG",
  "Story Rich",
  "Dating Sim",
  "Choice Matter",
  "Anime Games",
  "Adult VN",
  "Kinetic Novel",
  "Interactive Fiction",
  "Point & Click",
  "Mystery",
  "Thriller",
  "Adventure",
  "Dark Fantasy",
  "Gothic",
  "Fantasy",
  "Romance",
  "Drama",
  "Comedy",
  "Slice of Life",
  "Horror",
  "Psychological",
  "Supernatural",
  "Magic Academy",
  "School Life",
  "College",
  "Detective",
  "Crime",
  "Political Intrigue",
  "Sci-Fi",
  "Cyberpunk",
  "Post-Apocalyptic",
  "Time Loop",
  "Isekai",
  "Open World",
  "Life Sim",
  "Management",
  "Survival",
  "Strategy",
  "Puzzle",
  "Action RPG",
  "JRPG",
  "Tactical RPG",
  "Turn-Based",
  "Simulation",
  "Harem",
  "Multiple Endings",
  "Branching Paths",
  "Female Protagonist",
  "Male Protagonist",
  "Sandbox VN",
  "Netori",
  "Corruption",
  "Parody",
  "Monster Girl",
  "Otome",
  "Yuri",
  "Yaoi"
] as const;

export const ENGINES = ["Ren'Py", "Unity", "Unreal Engine", "RPG Maker", "Godot"] as const;

export const TAGS = [
  "18+",
  "Romance",
  "Fantasy",
  "Political Intrigue",
  "Morality",
  "College",
  "Cyberpunk",
  "Detective",
  "Magic Academy",
  "Time Loop",
  "Open World",
  "Companion Routes",
  "Mystery",
  "Heist",
  "Survival"
] as const;
