ALTER TABLE "Game" ADD COLUMN "coverZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Game" ADD COLUMN "coverPositionX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Game" ADD COLUMN "coverPositionY" INTEGER NOT NULL DEFAULT 50;
